# HubProxy Configuration File
# Copy this file to config.yaml and adjust the values

# Note: Sensitive values like webhook secrets should be provided via environment variables
# Use GITHUB_WEBHOOK_SECRET environment variable for the webhook secret

# Target URL to forward webhooks to
target_url: ""

# Log level (debug, info, warn, error)
log_level: info

# Validate that requests come from GitHub IPs
validate_ip: true

# Tailscale configuration
ts_authkey: ""
ts_hostname: hubproxy

# Database configuration
db_type: sqlite  # sqlite, mysql, or postgres
db_dsn: hubproxy.db
