# HubProxy Configuration File
# Copy this file to config.yaml and adjust the values

# Note: Sensitive values like webhook secrets should be provided via environment variables
# Use HUBPROXY_WEBHOOK_SECRET environment variable for the webhook secret

# Target URL to forward webhooks to
target-url: ""

# Log level (debug, info, warn, error)
log-level: info

# Validate that requests come from GitHub IPs
validate-ip: true

# Tailscale configuration
ts-authkey: ""
ts-hostname: hubproxy

# Database configuration
db-type: sqlite  # sqlite, mysql, or postgres
db-dsn: hubproxy.db
