// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqldb

import (
	"time"
)

type Event struct {
	ID         string    `json:"id"`
	Type       string    `json:"type"`
	Payload    []byte    `json:"payload"`
	CreatedAt  time.Time `json:"createdAt"`
	Status     string    `json:"status"`
	Error      string    `json:"error"`
	Repository string    `json:"repository"`
	Sender     string    `json:"sender"`
}
