// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqldb

import (
	"context"
)

type Querier interface {
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	DeleteEvent(ctx context.Context, id string) error
	GetEvent(ctx context.Context, id string) (Event, error)
	GetEventTypeStats(ctx context.Context, arg GetEventTypeStatsParams) ([]GetEventTypeStatsRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
